module Main exposing (..)

import Color exposing (Color)
import Html exposing (Html)
import Html.Attributes as A
import Ionicon


main : Html msg
main =
    Html.div [ A.style [ ( "margin", "0" ), ( "padding", "10px 20px" ), ( "min-height", "100vh" ), ( "font-family", "sans-serif" ), ( "background", "rgb(34,34,34)" ), ( "color", "rgb(230,230,230)" ) ] ]
        [ Html.h1 [ A.style [ ( "margin", "10px 0" ), ( "border-bottom", "1px solid rgba(230,230,230,.5)" ) ] ] [ Html.text "Ionicons!" ]
        , Html.div [ A.style [ ( "padding", "10px 0" ) ] ] (List.map viewIcon ionicons)
        , Html.div [ A.style [ ( "padding", "10px 0" ) ] ] (List.map viewAndroidIcon androidIcons)
        , Html.div [ A.style [ ( "padding", "10px 0" ) ] ] (List.map viewIOSIcon iosIcons)
        , Html.div [ A.style [ ( "padding", "10px 0" ) ] ] (List.map viewSocialIcon socialIcons)
        ]


viewIcon : (Int -> Color -> Html msg) -> Html msg
viewIcon icon =
    icon 32 (Color.hsl 1 1 1)


viewAndroidIcon : (Int -> Color -> Html msg) -> Html msg
viewAndroidIcon icon =
    icon 32 (Color.hsl 33.3 0.7 0.8)


viewIOSIcon : (Int -> Color -> Html msg) -> Html msg
viewIOSIcon icon =
    icon 32 (Color.hsl 66.7 0.7 0.8)


viewSocialIcon : (Int -> Color -> Html msg) -> Html msg
viewSocialIcon icon =
    icon 32 (Color.hsl 0 0.7 0.8)


ionicons : List (Int -> Color -> Html msg)
ionicons =
    [ Ionicon.alertCircled
    , Ionicon.alert
    , Ionicon.aperture
    , Ionicon.archive
    , Ionicon.arrowDownA
    , Ionicon.arrowDownB
    , Ionicon.arrowDownC
    , Ionicon.arrowExpand
    , Ionicon.arrowGraphDownLeft
    , Ionicon.arrowGraphDownRight
    , Ionicon.arrowGraphUpLeft
    , Ionicon.arrowGraphUpRight
    , Ionicon.arrowLeftA
    , Ionicon.arrowLeftB
    , Ionicon.arrowLeftC
    , Ionicon.arrowMove
    , Ionicon.arrowResize
    , Ionicon.arrowReturnLeft
    , Ionicon.arrowReturnRight
    , Ionicon.arrowRightA
    , Ionicon.arrowRightB
    , Ionicon.arrowRightC
    , Ionicon.arrowShrink
    , Ionicon.arrowSwap
    , Ionicon.arrowUpA
    , Ionicon.arrowUpB
    , Ionicon.arrowUpC
    , Ionicon.asterisk
    , Ionicon.at
    , Ionicon.backspaceOutline
    , Ionicon.backspace
    , Ionicon.bag
    , Ionicon.batteryCharging
    , Ionicon.batteryEmpty
    , Ionicon.batteryFull
    , Ionicon.batteryHalf
    , Ionicon.batteryLow
    , Ionicon.beaker
    , Ionicon.beer
    , Ionicon.bluetooth
    , Ionicon.bonfire
    , Ionicon.bookmark
    , Ionicon.bowtie
    , Ionicon.briefcase
    , Ionicon.bug
    , Ionicon.calculator
    , Ionicon.calendar
    , Ionicon.camera
    , Ionicon.card
    , Ionicon.cash
    , Ionicon.chatboxWorking
    , Ionicon.chatbox
    , Ionicon.chatboxes
    , Ionicon.chatbubbleWorking
    , Ionicon.chatbubble
    , Ionicon.chatbubbles
    , Ionicon.checkmarkCircled
    , Ionicon.checkmarkRound
    , Ionicon.checkmark
    , Ionicon.chevronDown
    , Ionicon.chevronLeft
    , Ionicon.chevronRight
    , Ionicon.chevronUp
    , Ionicon.clipboard
    , Ionicon.clock
    , Ionicon.closeCircled
    , Ionicon.closeRound
    , Ionicon.close
    , Ionicon.closedCaptioning
    , Ionicon.cloud
    , Ionicon.codeDownload
    , Ionicon.codeWorking
    , Ionicon.code
    , Ionicon.coffee
    , Ionicon.compass
    , Ionicon.compose
    , Ionicon.connectionBars
    , Ionicon.contrast
    , Ionicon.crop
    , Ionicon.cube
    , Ionicon.disc
    , Ionicon.documentText
    , Ionicon.document
    , Ionicon.drag
    , Ionicon.earth
    , Ionicon.easel
    , Ionicon.edit
    , Ionicon.egg
    , Ionicon.eject
    , Ionicon.emailUnread
    , Ionicon.email
    , Ionicon.erlenmeyerFlaskBubbles
    , Ionicon.erlenmeyerFlask
    , Ionicon.eyeDisabled
    , Ionicon.eye
    , Ionicon.female
    , Ionicon.filing
    , Ionicon.filmMarker
    , Ionicon.fireball
    , Ionicon.flag
    , Ionicon.flame
    , Ionicon.flashOff
    , Ionicon.flash
    , Ionicon.folder
    , Ionicon.forkRepo
    , Ionicon.fork
    , Ionicon.forward
    , Ionicon.funnel
    , Ionicon.gearA
    , Ionicon.gearB
    , Ionicon.grid
    , Ionicon.hammer
    , Ionicon.happyOutline
    , Ionicon.happy
    , Ionicon.headphone
    , Ionicon.heartBroken
    , Ionicon.heart
    , Ionicon.helpBuoy
    , Ionicon.helpCircled
    , Ionicon.help
    , Ionicon.home
    , Ionicon.icecream
    , Ionicon.image
    , Ionicon.images
    , Ionicon.informationCircled
    , Ionicon.information
    , Ionicon.ionic
    , Ionicon.ipad
    , Ionicon.iphone
    , Ionicon.ipod
    , Ionicon.jet
    , Ionicon.key
    , Ionicon.knife
    , Ionicon.laptop
    , Ionicon.leaf
    , Ionicon.levels
    , Ionicon.lightbulb
    , Ionicon.link
    , Ionicon.loadA
    , Ionicon.loadB
    , Ionicon.loadC
    , Ionicon.loadD
    , Ionicon.location
    , Ionicon.lockCombination
    , Ionicon.locked
    , Ionicon.logIn
    , Ionicon.logOut
    , Ionicon.loop
    , Ionicon.magnet
    , Ionicon.male
    , Ionicon.man
    , Ionicon.map
    , Ionicon.medkit
    , Ionicon.merge
    , Ionicon.micA
    , Ionicon.micB
    , Ionicon.micC
    , Ionicon.minusCircled
    , Ionicon.minusRound
    , Ionicon.minus
    , Ionicon.modelS
    , Ionicon.monitor
    , Ionicon.more
    , Ionicon.mouse
    , Ionicon.musicNote
    , Ionicon.naviconRound
    , Ionicon.navicon
    , Ionicon.navigate
    , Ionicon.network
    , Ionicon.noSmoking
    , Ionicon.nuclear
    , Ionicon.outlet
    , Ionicon.paintbrush
    , Ionicon.paintbucket
    , Ionicon.paperclip
    , Ionicon.pause
    , Ionicon.personAdd
    , Ionicon.personStalker
    , Ionicon.person
    , Ionicon.pieGraph
    , Ionicon.pin
    , Ionicon.pinpoint
    , Ionicon.pizza
    , Ionicon.plane
    , Ionicon.planet
    , Ionicon.play
    , Ionicon.playstation
    , Ionicon.plusCircled
    , Ionicon.plusRound
    , Ionicon.plus
    , Ionicon.podium
    , Ionicon.pound
    , Ionicon.power
    , Ionicon.pricetag
    , Ionicon.pricetags
    , Ionicon.printer
    , Ionicon.pullRequest
    , Ionicon.qrScanner
    , Ionicon.quote
    , Ionicon.radioWaves
    , Ionicon.record
    , Ionicon.refresh
    , Ionicon.replyAll
    , Ionicon.reply
    , Ionicon.ribbonA
    , Ionicon.ribbonB
    , Ionicon.sadOutline
    , Ionicon.sad
    , Ionicon.scissors
    , Ionicon.search
    , Ionicon.settings
    , Ionicon.share
    , Ionicon.shuffle
    , Ionicon.skipBackward
    , Ionicon.skipForward
    , Ionicon.soupCanOutline
    , Ionicon.soupCan
    , Ionicon.speakerphone
    , Ionicon.speedometer
    , Ionicon.spoon
    , Ionicon.star
    , Ionicon.starBars
    , Ionicon.steam
    , Ionicon.stop
    , Ionicon.thermometer
    , Ionicon.thumbsdown
    , Ionicon.thumbsup
    , Ionicon.toggleFilled
    , Ionicon.toggle
    , Ionicon.transgender
    , Ionicon.trashA
    , Ionicon.trashB
    , Ionicon.trophy
    , Ionicon.tshirtOutline
    , Ionicon.tshirt
    , Ionicon.umbrella
    , Ionicon.university
    , Ionicon.unlocked
    , Ionicon.upload
    , Ionicon.usb
    , Ionicon.videocamera
    , Ionicon.volumeHigh
    , Ionicon.volumeLow
    , Ionicon.volumeMedium
    , Ionicon.volumeMute
    , Ionicon.wand
    , Ionicon.waterdrop
    , Ionicon.wifi
    , Ionicon.wineglass
    , Ionicon.woman
    , Ionicon.wrench
    , Ionicon.xbox
    ]


androidIcons : List (Int -> Color -> Html msg)
androidIcons =
    [ Ionicon.androidAddCircle
    , Ionicon.androidAdd
    , Ionicon.androidAlarmClock
    , Ionicon.androidAlert
    , Ionicon.androidApps
    , Ionicon.androidArchive
    , Ionicon.androidArrowBack
    , Ionicon.androidArrowDown
    , Ionicon.androidArrowDropdownCircle
    , Ionicon.androidArrowDropdown
    , Ionicon.androidArrowDropleftCircle
    , Ionicon.androidArrowDropleft
    , Ionicon.androidArrowDroprightCircle
    , Ionicon.androidArrowDropright
    , Ionicon.androidArrowDropupCircle
    , Ionicon.androidArrowDropup
    , Ionicon.androidArrowForward
    , Ionicon.androidArrowUp
    , Ionicon.androidAttach
    , Ionicon.androidBar
    , Ionicon.androidBicycle
    , Ionicon.androidBoat
    , Ionicon.androidBookmark
    , Ionicon.androidBulb
    , Ionicon.androidBus
    , Ionicon.androidCalendar
    , Ionicon.androidCall
    , Ionicon.androidCamera
    , Ionicon.androidCancel
    , Ionicon.androidCar
    , Ionicon.androidCart
    , Ionicon.androidChat
    , Ionicon.androidCheckboxBlank
    , Ionicon.androidCheckboxOutlineBlank
    , Ionicon.androidCheckboxOutline
    , Ionicon.androidCheckbox
    , Ionicon.androidCheckmarkCircle
    , Ionicon.androidClipboard
    , Ionicon.androidClose
    , Ionicon.androidCloudCircle
    , Ionicon.androidCloudDone
    , Ionicon.androidCloudOutline
    , Ionicon.androidCloud
    , Ionicon.androidColorPalette
    , Ionicon.androidCompass
    , Ionicon.androidContact
    , Ionicon.androidContacts
    , Ionicon.androidContract
    , Ionicon.androidCreate
    , Ionicon.androidDelete
    , Ionicon.androidDesktop
    , Ionicon.androidDocument
    , Ionicon.androidDoneAll
    , Ionicon.androidDone
    , Ionicon.androidDownload
    , Ionicon.androidDrafts
    , Ionicon.androidExit
    , Ionicon.androidExpand
    , Ionicon.androidFavoriteOutline
    , Ionicon.androidFavorite
    , Ionicon.androidFilm
    , Ionicon.androidFolderOpen
    , Ionicon.androidFolder
    , Ionicon.androidFunnel
    , Ionicon.androidGlobe
    , Ionicon.androidHand
    , Ionicon.androidHangout
    , Ionicon.androidHappy
    , Ionicon.androidHome
    , Ionicon.androidImage
    , Ionicon.androidLaptop
    , Ionicon.androidList
    , Ionicon.androidLocate
    , Ionicon.androidLock
    , Ionicon.androidMail
    , Ionicon.androidMap
    , Ionicon.androidMenu
    , Ionicon.androidMicrophoneOff
    , Ionicon.androidMicrophone
    , Ionicon.androidMoreHorizontal
    , Ionicon.androidMoreVertical
    , Ionicon.androidNavigate
    , Ionicon.androidNotificationsNone
    , Ionicon.androidNotificationsOff
    , Ionicon.androidNotifications
    , Ionicon.androidOpen
    , Ionicon.androidOptions
    , Ionicon.androidPeople
    , Ionicon.androidPersonAdd
    , Ionicon.androidPerson
    , Ionicon.androidPhoneLandscape
    , Ionicon.androidPhonePortrait
    , Ionicon.androidPin
    , Ionicon.androidPlane
    , Ionicon.androidPlaystore
    , Ionicon.androidPrint
    , Ionicon.androidRadioButtonOff
    , Ionicon.androidRadioButtonOn
    , Ionicon.androidRefresh
    , Ionicon.androidRemoveCircle
    , Ionicon.androidRemove
    , Ionicon.androidRestaurant
    , Ionicon.androidSad
    , Ionicon.androidSearch
    , Ionicon.androidSend
    , Ionicon.androidSettings
    , Ionicon.androidShareAlt
    , Ionicon.androidShare
    , Ionicon.androidStarHalf
    , Ionicon.androidStarOutline
    , Ionicon.androidStar
    , Ionicon.androidStopwatch
    , Ionicon.androidSubway
    , Ionicon.androidSunny
    , Ionicon.androidSync
    , Ionicon.androidTextsms
    , Ionicon.androidTime
    , Ionicon.androidTrain
    , Ionicon.androidUnlock
    , Ionicon.androidUpload
    , Ionicon.androidVolumeDown
    , Ionicon.androidVolumeMute
    , Ionicon.androidVolumeOff
    , Ionicon.androidVolumeUp
    , Ionicon.androidWalk
    , Ionicon.androidWarning
    , Ionicon.androidWatch
    , Ionicon.androidWifi
    ]


iosIcons : List (Int -> Color -> Html msg)
iosIcons =
    [ Ionicon.iosAlarmOutline
    , Ionicon.iosAlarm
    , Ionicon.iosAlbumsOutline
    , Ionicon.iosAlbums
    , Ionicon.iosAmericanfootballOutline
    , Ionicon.iosAmericanfootball
    , Ionicon.iosAnalyticsOutline
    , Ionicon.iosAnalytics
    , Ionicon.iosArrowBack
    , Ionicon.iosArrowDown
    , Ionicon.iosArrowForward
    , Ionicon.iosArrowLeft
    , Ionicon.iosArrowRight
    , Ionicon.iosArrowThinDown
    , Ionicon.iosArrowThinLeft
    , Ionicon.iosArrowThinRight
    , Ionicon.iosArrowThinUp
    , Ionicon.iosArrowUp
    , Ionicon.iosAtOutline
    , Ionicon.iosAt
    , Ionicon.iosBarcodeOutline
    , Ionicon.iosBarcode
    , Ionicon.iosBaseballOutline
    , Ionicon.iosBaseball
    , Ionicon.iosBasketballOutline
    , Ionicon.iosBasketball
    , Ionicon.iosBellOutline
    , Ionicon.iosBell
    , Ionicon.iosBodyOutline
    , Ionicon.iosBody
    , Ionicon.iosBoltOutline
    , Ionicon.iosBolt
    , Ionicon.iosBookOutline
    , Ionicon.iosBook
    , Ionicon.iosBookmarksOutline
    , Ionicon.iosBookmarks
    , Ionicon.iosBoxOutline
    , Ionicon.iosBox
    , Ionicon.iosBriefcaseOutline
    , Ionicon.iosBriefcase
    , Ionicon.iosBrowsersOutline
    , Ionicon.iosBrowsers
    , Ionicon.iosCalculatorOutline
    , Ionicon.iosCalculator
    , Ionicon.iosCalendarOutline
    , Ionicon.iosCalendar
    , Ionicon.iosCameraOutline
    , Ionicon.iosCamera
    , Ionicon.iosCartOutline
    , Ionicon.iosCart
    , Ionicon.iosChatboxesOutline
    , Ionicon.iosChatboxes
    , Ionicon.iosChatbubbleOutline
    , Ionicon.iosChatbubble
    , Ionicon.iosCheckmarkEmpty
    , Ionicon.iosCheckmarkOutline
    , Ionicon.iosCheckmark
    , Ionicon.iosCircleFilled
    , Ionicon.iosCircleOutline
    , Ionicon.iosClockOutline
    , Ionicon.iosClock
    , Ionicon.iosCloseEmpty
    , Ionicon.iosCloseOutline
    , Ionicon.iosClose
    , Ionicon.iosCloudDownloadOutline
    , Ionicon.iosCloudDownload
    , Ionicon.iosCloudOutline
    , Ionicon.iosCloudUploadOutline
    , Ionicon.iosCloudUpload
    , Ionicon.iosCloud
    , Ionicon.iosCloudyNightOutline
    , Ionicon.iosCloudyNight
    , Ionicon.iosCloudyOutline
    , Ionicon.iosCloudy
    , Ionicon.iosCogOutline
    , Ionicon.iosCog
    , Ionicon.iosColorFilterOutline
    , Ionicon.iosColorFilter
    , Ionicon.iosColorWandOutline
    , Ionicon.iosColorWand
    , Ionicon.iosComposeOutline
    , Ionicon.iosCompose
    , Ionicon.iosContactOutline
    , Ionicon.iosContact
    , Ionicon.iosCopyOutline
    , Ionicon.iosCopy
    , Ionicon.iosCropStrong
    , Ionicon.iosCrop
    , Ionicon.iosDownloadOutline
    , Ionicon.iosDownload
    , Ionicon.iosDrag
    , Ionicon.iosEmailOutline
    , Ionicon.iosEmail
    , Ionicon.iosEyeOutline
    , Ionicon.iosEye
    , Ionicon.iosFastforwardOutline
    , Ionicon.iosFastforward
    , Ionicon.iosFilingOutline
    , Ionicon.iosFiling
    , Ionicon.iosFilmOutline
    , Ionicon.iosFilm
    , Ionicon.iosFlagOutline
    , Ionicon.iosFlag
    , Ionicon.iosFlameOutline
    , Ionicon.iosFlame
    , Ionicon.iosFlaskOutline
    , Ionicon.iosFlask
    , Ionicon.iosFlowerOutline
    , Ionicon.iosFlower
    , Ionicon.iosFolderOutline
    , Ionicon.iosFolder
    , Ionicon.iosFootballOutline
    , Ionicon.iosFootball
    , Ionicon.iosGameControllerAOutline
    , Ionicon.iosGameControllerA
    , Ionicon.iosGameControllerBOutline
    , Ionicon.iosGameControllerB
    , Ionicon.iosGearOutline
    , Ionicon.iosGear
    , Ionicon.iosGlassesOutline
    , Ionicon.iosGlasses
    , Ionicon.iosGridViewOutline
    , Ionicon.iosGridView
    , Ionicon.iosHeartOutline
    , Ionicon.iosHeart
    , Ionicon.iosHelpEmpty
    , Ionicon.iosHelpOutline
    , Ionicon.iosHelp
    , Ionicon.iosHomeOutline
    , Ionicon.iosHome
    , Ionicon.iosInfiniteOutline
    , Ionicon.iosInfinite
    , Ionicon.iosInformationEmpty
    , Ionicon.iosInformationOutline
    , Ionicon.iosInformation
    , Ionicon.iosIonicOutline
    , Ionicon.iosKeypadOutline
    , Ionicon.iosKeypad
    , Ionicon.iosLightbulbOutline
    , Ionicon.iosLightbulb
    , Ionicon.iosListOutline
    , Ionicon.iosList
    , Ionicon.iosLocationOutline
    , Ionicon.iosLocation
    , Ionicon.iosLockedOutline
    , Ionicon.iosLocked
    , Ionicon.iosLoopStrong
    , Ionicon.iosLoop
    , Ionicon.iosMedicalOutline
    , Ionicon.iosMedical
    , Ionicon.iosMedkitOutline
    , Ionicon.iosMedkit
    , Ionicon.iosMicOff
    , Ionicon.iosMicOutline
    , Ionicon.iosMic
    , Ionicon.iosMinusEmpty
    , Ionicon.iosMinusOutline
    , Ionicon.iosMinus
    , Ionicon.iosMonitorOutline
    , Ionicon.iosMonitor
    , Ionicon.iosMoonOutline
    , Ionicon.iosMoon
    , Ionicon.iosMoreOutline
    , Ionicon.iosMore
    , Ionicon.iosMusicalNote
    , Ionicon.iosMusicalNotes
    , Ionicon.iosNavigateOutline
    , Ionicon.iosNavigate
    , Ionicon.iosNutritionOutline
    , Ionicon.iosNutrition
    , Ionicon.iosPaperOutline
    , Ionicon.iosPaper
    , Ionicon.iosPaperplaneOutline
    , Ionicon.iosPaperplane
    , Ionicon.iosPartlySunnyOutline
    , Ionicon.iosPartlySunny
    , Ionicon.iosPauseOutline
    , Ionicon.iosPause
    , Ionicon.iosPawOutline
    , Ionicon.iosPaw
    , Ionicon.iosPeopleOutline
    , Ionicon.iosPeople
    , Ionicon.iosPersonOutline
    , Ionicon.iosPerson
    , Ionicon.iosPersonaddOutline
    , Ionicon.iosPersonadd
    , Ionicon.iosPhotosOutline
    , Ionicon.iosPhotos
    , Ionicon.iosPieOutline
    , Ionicon.iosPie
    , Ionicon.iosPintOutline
    , Ionicon.iosPint
    , Ionicon.iosPlayOutline
    , Ionicon.iosPlay
    , Ionicon.iosPlusEmpty
    , Ionicon.iosPlusOutline
    , Ionicon.iosPlus
    , Ionicon.iosPricetagOutline
    , Ionicon.iosPricetag
    , Ionicon.iosPricetagsOutline
    , Ionicon.iosPricetags
    , Ionicon.iosPrinterOutline
    , Ionicon.iosPrinter
    , Ionicon.iosPulseStrong
    , Ionicon.iosPulse
    , Ionicon.iosRainyOutline
    , Ionicon.iosRainy
    , Ionicon.iosRecordingOutline
    , Ionicon.iosRecording
    , Ionicon.iosRedoOutline
    , Ionicon.iosRedo
    , Ionicon.iosRefreshEmpty
    , Ionicon.iosRefreshOutline
    , Ionicon.iosRefresh
    , Ionicon.iosReload
    , Ionicon.iosReverseCameraOutline
    , Ionicon.iosReverseCamera
    , Ionicon.iosRewindOutline
    , Ionicon.iosRewind
    , Ionicon.iosRoseOutline
    , Ionicon.iosRose
    , Ionicon.iosSearchStrong
    , Ionicon.iosSearch
    , Ionicon.iosSettingsStrong
    , Ionicon.iosSettings
    , Ionicon.iosShuffleStrong
    , Ionicon.iosShuffle
    , Ionicon.iosSkipbackwardOutline
    , Ionicon.iosSkipbackward
    , Ionicon.iosSkipforwardOutline
    , Ionicon.iosSkipforward
    , Ionicon.iosSnowy
    , Ionicon.iosSpeedometerOutline
    , Ionicon.iosSpeedometer
    , Ionicon.iosStarHalf
    , Ionicon.iosStarOutline
    , Ionicon.iosStar
    , Ionicon.iosStopwatchOutline
    , Ionicon.iosStopwatch
    , Ionicon.iosSunnyOutline
    , Ionicon.iosSunny
    , Ionicon.iosTelephoneOutline
    , Ionicon.iosTelephone
    , Ionicon.iosTennisballOutline
    , Ionicon.iosTennisball
    , Ionicon.iosThunderstormOutline
    , Ionicon.iosThunderstorm
    , Ionicon.iosTimeOutline
    , Ionicon.iosTime
    , Ionicon.iosTimerOutline
    , Ionicon.iosTimer
    , Ionicon.iosToggleOutline
    , Ionicon.iosToggle
    , Ionicon.iosTrashOutline
    , Ionicon.iosTrash
    , Ionicon.iosUndoOutline
    , Ionicon.iosUndo
    , Ionicon.iosUnlockedOutline
    , Ionicon.iosUnlocked
    , Ionicon.iosUploadOutline
    , Ionicon.iosUpload
    , Ionicon.iosVideocamOutline
    , Ionicon.iosVideocam
    , Ionicon.iosVolumeHigh
    , Ionicon.iosVolumeLow
    , Ionicon.iosWineglassOutline
    , Ionicon.iosWineglass
    , Ionicon.iosWorldOutline
    , Ionicon.iosWorld
    ]


socialIcons : List (Int -> Color -> Html msg)
socialIcons =
    [ Ionicon.socialAndroidOutline
    , Ionicon.socialAndroid
    , Ionicon.socialAngularOutline
    , Ionicon.socialAngular
    , Ionicon.socialAppleOutline
    , Ionicon.socialApple
    , Ionicon.socialBitcoinOutline
    , Ionicon.socialBitcoin
    , Ionicon.socialBufferOutline
    , Ionicon.socialBuffer
    , Ionicon.socialChromeOutline
    , Ionicon.socialChrome
    , Ionicon.socialCodepenOutline
    , Ionicon.socialCodepen
    , Ionicon.socialCss3Outline
    , Ionicon.socialCss3
    , Ionicon.socialDesignernewsOutline
    , Ionicon.socialDesignernews
    , Ionicon.socialDribbbleOutline
    , Ionicon.socialDribbble
    , Ionicon.socialDropboxOutline
    , Ionicon.socialDropbox
    , Ionicon.socialEuroOutline
    , Ionicon.socialEuro
    , Ionicon.socialFacebookOutline
    , Ionicon.socialFacebook
    , Ionicon.socialFoursquareOutline
    , Ionicon.socialFoursquare
    , Ionicon.socialFreebsdDevil
    , Ionicon.socialGithubOutline
    , Ionicon.socialGithub
    , Ionicon.socialGoogleOutline
    , Ionicon.socialGoogle
    , Ionicon.socialGoogleplusOutline
    , Ionicon.socialGoogleplus
    , Ionicon.socialHackernewsOutline
    , Ionicon.socialHackernews
    , Ionicon.socialHtml5Outline
    , Ionicon.socialHtml5
    , Ionicon.socialInstagram
    , Ionicon.socialJavascriptOutline
    , Ionicon.socialJavascript
    , Ionicon.socialLinkedinOutline
    , Ionicon.socialLinkedin
    , Ionicon.socialMarkdown
    , Ionicon.socialNodejs
    , Ionicon.socialOctocat
    , Ionicon.socialPinterestOutline
    , Ionicon.socialPinterest
    , Ionicon.socialPython
    , Ionicon.socialRedditOutline
    , Ionicon.socialReddit
    , Ionicon.socialRssOutline
    , Ionicon.socialRss
    , Ionicon.socialSass
    , Ionicon.socialSkypeOutline
    , Ionicon.socialSkype
    , Ionicon.socialSnapchatOutline
    , Ionicon.socialSnapchat
    , Ionicon.socialTumblrOutline
    , Ionicon.socialTumblr
    , Ionicon.socialTux
    , Ionicon.socialTwitchOutline
    , Ionicon.socialTwitch
    , Ionicon.socialTwitterOutline
    , Ionicon.socialTwitter
    , Ionicon.socialUsdOutline
    , Ionicon.socialUsd
    , Ionicon.socialVimeoOutline
    , Ionicon.socialVimeo
    , Ionicon.socialWhatsappOutline
    , Ionicon.socialWhatsapp
    , Ionicon.socialWindowsOutline
    , Ionicon.socialWindows
    , Ionicon.socialWordpressOutline
    , Ionicon.socialWordpress
    , Ionicon.socialYahooOutline
    , Ionicon.socialYahoo
    , Ionicon.socialYenOutline
    , Ionicon.socialYen
    , Ionicon.socialYoutubeOutline
    , Ionicon.socialYoutube
    ]
